#!/usr/bin/env bash

# add a word to the dictionary, optionally with prefix / suffix tags

# usage:
# ~ $ add word[/TAGS]

# remove any dictionary tags from the end i.e. rhywedd/M becomes rhywedd
gair=$(sed -e "s|/.*||" <<< "$1")

if grep -Fxq "$gair" ./dictionaries/word_list.txt ; then
	echo "\"$gair\" is already in word_list.txt"
else
	echo "Adding word \"$gair\" to word_list.txt"
	# Add word
	echo "$gair" >> dictionaries/word_list.txt
	# Sort alphabetically
	sort -u dictionaries/word_list.txt > dictionaries/list.tmp
	# Replace the old word list
	mv dictionaries/list.tmp dictionaries/word_list.txt

	printf "Add word \"$1\" to mwy.dic? "
	if [[ "$(read -e -p '[y/n] '; echo $REPLY)" == [Yy]* ]] ; then
		# Add word
		echo $1 >> dictionaries/mwy.dic
		# Write number of lines to tmp
		tail -n +2 dictionaries/mwy.dic | sort -u | wc -l > dictionaries/dict.tmp
		# Write sorted words to tmp
		tail -n +2 dictionaries/mwy.dic | sort -u >> dictionaries/dict.tmp
		# Copy tmp back to mwy.dic
		mv dictionaries/dict.tmp dictionaries/mwy.dic
		echo "Added word."
	fi
fi

# contains any unknown words in the word list
anhysbys=$(hunspell -L -d dictionaries/mwy dictionaries/word_list.txt)
if [[ -n "$anhysbys" ]] ; then
	echo "The dictionary does not recognise the following:"
	echo "$anhysbys"
else
	echo "The dictionary recognises everything in the word list."
	#echo ""
fi
