#!/bin/bash

###
# usage: ./teclyn -[a, b, e]
# -a gair
#       adds 'gair' to dictionary (may include
#       dictionary tags on the end e.g. /AFG).
# -b
#       builds the libreoffice package.
# -e gair
#       use 'wordforms' from hunspell to expand
#       the given word with all relevant
#       permitted affixes in the dictionary.
###

parse () {
	###
	# get command line options
	###
	case "$1" in
		-a|--add)
			ychwanegu "$2"
			shift
			;;
		-e|--expand)
			ystyried "$2"
			shift
			;;
		-b|--build)
			adeiladu
			shift
			;;
		--)
			shift
			break
			;;
		*)
			echo "Programming error"
			exit 3
			;;
	esac
}

ystyried () {
	###
	# expand a word with all available relevant affixes
	###
	./wordforms dictionaries/cy_GB.aff dictionaries/cy_GB.dic "$1" | sort -u
}

adeiladu () {
	###
	# make the libreoffice extension
	###
	echo "Building..."
	#clean the folder of zips and oxts (which are just renamed zips)
	mv *.oxt archive/ 2> /dev/null
	mv *.zip archive/ 2> /dev/null

	# figure out which version we're building
	version=$(grep -rnw './description.xml' -e '<version value=')
	# remove xml stuff to just have the version data
	version=${version/*value=\"/}
	version=${version/\"*/} 

	# zip the latest files
	zip -qr out.zip description/ META-INF/ dictionaries/cy_GB.dic dictionaries/cy_GB.aff dictionaries/hen.dic dictionaries/hen.aff baner_cymreig.png description.xml dictionaries.xcu LICENSE README.txt

	# rename the latest zip to oxt
	mv out.zip libreoffice-geiriadur-$version.oxt
	echo "Built."
}

ychwanegu () {
	###
	# add a word to the dictionary, optionally with prefix / suffix tags
	###
	# remove any dictionary tags from the end i.e. rhywedd/M becomes rhywedd
	gair=$(sed -e "s|/.*||" <<< "$1")
	anhysbys=$(hunspell -L -d dictionaries/cy_GB <<< "$gair")

	if [[ -n "$anhysbys" ]] ; then
		echo "Adding word \"$gair\" to dictionary"
		# Add word
		echo "$gair" >> dictionaries/word_list.txt
		echo "$1" >> dictionaries/cy_GB.dic
		# Write number of lines to tmp
		tail -n +2 dictionaries/cy_GB.dic | sort -u | wc -l > dictionaries/dict.tmp
		# Write sorted words to tmp
		tail -n +2 dictionaries/cy_GB.dic | sort -u >> dictionaries/dict.tmp
		# Copy tmp back to mwy.dic
		mv dictionaries/dict.tmp dictionaries/cy_GB.dic
		echo "Added word."
	else
		echo "\"$gair\" is already in dictionary"
	fi

	# contains any unknown words in the word list
	anhysbys=$(hunspell -L -d dictionaries/cy_GB dictionaries/word_list.txt)
	if [[ -n "$anhysbys" ]] ; then
		echo "The dictionary does not recognise the following:"
		echo "$anhysbys"
	else
		#echo "The dictionary recognises everything in the word list."
		echo ""
	fi
}


parse $1 $2
